[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
multisig_program = "9tX4QfdBjXLUXiV1htgqcLedzygnm87zh58DWENv59f1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/wanaqil/devnet-wallet.json"

[programs.devnet]
multisig_program = "9tX4QfdBjXLUXiV1htgqcLedzygnm87zh58DWENv59f1"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
